import QRCode from 'qrcode';

export interface QrCodeDetails {
  projectTitle?: string;
  projectRefNo?: string;
  dateTimeSubmitted?: string;
  documentName?: string;
  documentNumber?: string;
  companyName?: string;
  procuringEntity?: string;
  solicitationNo?: string;
  logoUrl?: string; // Optional custom logo image URL or base64 string
  documentCategory?: string;
  generatedBy?: string;
}

/**
 * Formats all requested metadata fields into a structured, easily scannable text payload.
 */
export const formatQrPayload = (details: QrCodeDetails): string => {
  const parts: string[] = [];

  if (details.projectTitle) parts.push(`Project Name: ${details.projectTitle}`);
  if (details.projectRefNo) parts.push(`Reference No: ${details.projectRefNo}`);
  if (details.dateTimeSubmitted) parts.push(`Submitted Date/Time: ${details.dateTimeSubmitted}`);
  if (details.documentName) parts.push(`Document Name: ${details.documentName}`);
  if (details.documentNumber) parts.push(`Document No: ${details.documentNumber}`);
  if (details.companyName) parts.push(`Company Name: ${details.companyName}`);
  if (details.procuringEntity) parts.push(`Procuring Entity: ${details.procuringEntity}`);
  if (details.solicitationNo) parts.push(`Solicitation No: ${details.solicitationNo}`);
  if (details.documentCategory) parts.push(`Document Category: ${details.documentCategory}`);
  if (details.generatedBy) parts.push(`Generated By: ${details.generatedBy}`);

  return parts.join('\n');
};

/**
 * Helper function to safely load an image URL into an HTMLImageElement
 */
const loadImage = (src: string): Promise<HTMLImageElement> => {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = () => resolve(img);
    img.onerror = (err) => reject(err);
    img.src = src;
  });
};

/**
 * Generates a high-resolution, scannable QR code Data URL with a center logo overlay.
 */
export const generateQrCodeDataUrl = async (details: QrCodeDetails): Promise<string> => {
  try {
    const textPayload = formatQrPayload(details);

    if (!textPayload) {
      return '';
    }

    const canvasSize = 500; // Canvas dimensions for crisp rendering
    const canvas = document.createElement('canvas');
    canvas.width = canvasSize;
    canvas.height = canvasSize;

    // Render QR Code with High ('H') Error Correction Level (allows up to ~30% coverage for logo)
    await QRCode.toCanvas(canvas, textPayload, {
      width: canvasSize,
      margin: 2,
      errorCorrectionLevel: 'H',
      color: {
        dark: '#000000',
        light: '#FFFFFF'
      }
    });

    const ctx = canvas.getContext('2d');
    if (!ctx) return canvas.toDataURL('image/png');

    // Draw logo in the center if provided
    if (details.logoUrl) {
      try {
        const logo = await loadImage(details.logoUrl);

        // Logo sizing: Keep within 22% of QR width to ensure readability
        const logoSize = canvasSize * 0.22;
        const centerPos = (canvasSize - logoSize) / 2;
        const padding = 6;

        // White background box behind the logo to clear background QR dots
        ctx.fillStyle = '#FFFFFF';
        ctx.fillRect(
          centerPos - padding / 2,
          centerPos - padding / 2,
          logoSize + padding,
          logoSize + padding
        );

        // Draw company logo
        ctx.drawImage(logo, centerPos, centerPos, logoSize, logoSize);
      } catch (err) {
        console.warn('Could not overlay company logo onto QR code, generating clear QR instead:', err);
      }
    }

    return canvas.toDataURL('image/png');
  } catch (err) {
    console.error('Failed to generate QR Code Data URL:', err);
    return '';
  }
};